version: '3'

networks:
  default: {}

services:
  # The Database
  mysql:
    container_name: nxb_mysql57_con
    build:
      context: ./mysql
    volumes:
      - ./mysql/loging.cnf:/etc/mysql/conf.d/loging.cnf
    ports:
      - 4406:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: blogdb
      MYSQL_USER: binhnx
      MYSQL_PASSWORD: 123456

  # The server
  backend:
    container_name: nxb_server
    build:
      context: ./backend
    working_dir: /var/www/html/source_code
    volumes:
      - ${DMM_BACKEND_PATH}:/var/www/html/source_code
      - ./backend/apache/logs:/var/log/httpd
    ports:
      - 7004:80
    links:
      - mysql
    depends_on:
      - mysql
    env_file: .env